Lab3.4/Models/Enterprise.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Lab3._4.Models
{
    public class Enterprise
    {
        public string ID { get; set; }
        public string Name { get; set; }
    }
}

Lab3.4/Controllers/HelperRazorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab3._4.Controllers
{
    public class HelperRazorController : Controller
    {
        // GET: HelperRazor
        public ActionResult FormRegister()
        {
            // Tạo list cho droplist
            ViewBag.listEnterprise = new List<Models.Enterprise>()
            {
                new Models.Enterprise(){ID="0",Name="-- Chọn Doanh Nghiệp --"},
                new Models.Enterprise(){ID="DVNN",Name="Đơn vị sự nghiệp nhà nước"},
                new Models.Enterprise(){ID="LT",Name="Lập trình ASP.NET"},
                new Models.Enterprise(){ID="LT1",Name="Lập trình Java"},
                new Models.Enterprise(){ID="LT2",Name="Lập trình PHP"},
                new Models.Enterprise(){ID="LT3",Name="Lập trình Android"},
                new Models.Enterprise(){ID="QT",Name="Quản trị FPT"},
                new Models.Enterprise(){ID="KT",Name="Kế toán"},
                new Models.Enterprise(){ID="BB",Name="Buôn bán ma túy"},
                new Models.Enterprise(){ID="PT",Name="Phân tích thiết kế"},
            };
            return View();
        }
        public ActionResult Register()
        {
            // Lấy giá trị được các trường đẩy lên server khi submit
            string GetEmail = "";
            TempData["UNameDV"] = Request["txtNameDV"];
            TempData["SLNV"] = Request["txtSLNV"];
            TempData["Address"] = Request["txtAddress"];
            TempData["NguoiLH"] = Request["txtNguoiLH"];
            TempData["SDT"] = Request["txtSDT"];
            TempData["Fax"] = Request["txtSoFax"];
            TempData["Email"] = Request["txtEmail"];
            TempData["DCWeb"] = Request["txtDCWeb"];
            TempData["UNameDN"] = Request["txtNameDN"];
            TempData["MK"] = Request["txtPass"];
            TempData["letter"] = GetEmail;
            return View();
        }
    }
}

Lab3.4/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab3._4.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Lab3.4/Views/HelperRazor/FormRegister.cshtml
@{
    /**/

    ViewBag.Title = "FormRegister";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Thông tin đăng ký</h2>
<br />
@{
    Html.BeginForm("Register", "HelperRazor", FormMethod.Get);
<table class="table table-bordered">
    <caption class="alert-info" style="color:#FFFfff;"><h4>Thông tin về đơn vị tuyển</h4></caption>
    <tr>
        <td>@Html.Label("Tên đơn vị tuyển (*)")</td>
        <td>@Html.TextBox("txtNameDV")</td>
    </tr>
    <tr>
        <td>@Html.Label("Loại hình doanh nghiệp (*)")</td>
        <td>@Html.DropDownList("Enterprise", new SelectList(ViewBag.listEnterprise, "ID", "Name"))</td>
    </tr>
    <tr>
        <td>@Html.Label("Số lượng nhân viên")</td>
        <td>@Html.TextBox("txtSLNV")</td>
    </tr>

    <caption class="alert-info" style="color:#FFFfff;"><h4>Thông tin liên hệ</h4></caption>
    <tr>
        <td>@Html.Label("Địa chỉ (*)")</td>
        <td>@Html.TextArea("txtAddress")</td>
    </tr>
    <tr>
        <td>@Html.Label("Người liên hệ (*)")</td>
        <td>@Html.TextBox("txtNguoiLH")</td>
    </tr>
    <tr>
        <td>@Html.Label("Số điện thoại (*)")</td>
        <td>@Html.TextBox("txtSDT")</td>
    </tr>
    <tr>
        <td>@Html.Label("Số Fax")</td>
        <td>@Html.TextBox("txtSoFax")</td>
    </tr>
    <tr>
        <td>@Html.Label("Email")</td>
        <td>@Html.TextBox("txtEmail")</td>
    </tr>
    <tr>
        <td>@Html.Label("Địa chỉ Website")</td>
        <td>@Html.TextBox("txtDCWeb")</td>
    </tr>

    <caption class="alert-info" style="color:#FFFfff;"><h4>Thông tin Đăng nhập</h4></caption>
    <tr>
        <td>@Html.Label("Tên đăng nhập (*)")</td>
        <td>@Html.TextBox("txtNameDN")</td>
    </tr>
    <tr>
        <td>@Html.Label("Mật khẩu (*)")</td>
        <td>@Html.Password("txtPass")</td>
    </tr>
    <tr>
        <td>@Html.Label("Xác nhận mật khẩu")</td>
        <td>@Html.TextBox("txtCfPass")</td>
    </tr>

    <caption class="alert-info" style="color:#FFFfff;"><h4>Nhận E-mail</h4></caption>
    <tr>
        <td>@Html.Label("Nhận thư điện tử")</td>
        <td>
            @Html.RadioButton("letter", "Nhận", true)Nhận
            @Html.RadioButton("letter", "Không")Không nhận
        </td>
    </tr>
    <tr>
        <td></td>
        <td>
            <input type="submit" value="Cập nhật" />
            <input type="submit" value="Hủy bỏ" />
        </td>
    </tr>
</table>
}

Lab3.4/Views/HelperRazor/Register.cshtml
@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Thông tin đăng ký</h2>
<table class="table table-bordered">
    <tr>
        <td>Tên đơn vị tuyển :</td>
        <td>@TempData["UNameDV"]</td>
    </tr>

    <tr>
        <td>Số lượng nhân viên :</td>
        <td>@TempData["SLNV"]</td>
    </tr>

    <tr>
        <td>Địa chỉ :</td>
        <td>@TempData["Address"]</td>
    </tr>

    <tr>
        <td>Người liên hệ :</td>
        <td>@TempData["NguoiLH"]</td>
    </tr>

    <tr>
        <td>Số điện thoại :</td>
        <td>@TempData["SDT"]</td>
    </tr>

    <tr>
        <td>Số Fax :</td>
        <td>@TempData["Fax"]</td>
    </tr>

    <tr>
        <td>Email :</td>
        <td>@TempData["Email"]</td>
    </tr>

    <tr>
        <td>Địa chỉ Website :</td>
        <td>@TempData["DCWeb"]</td>
    </tr>

    <tr>
        <td>Tên đăng nhập :</td>
        <td>@TempData["UNameDN"]</td>
    </tr>

    <tr>
        <td>Mật khẩu :</td>
        <td>@TempData["MK"]</td>
    </tr>

    <tr>
        <td>Nhận thư điện tử :</td>
        <td>@TempData["letter"]</td>
    </tr>
</table>

Lab3.4/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Lab3.4/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Lab3.4/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Lab3.4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("DEVMASTER.vn", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-right navbar-nav">
                    <li>@Html.ActionLink("Đăng ký", "FormRegister", "HelperRazor")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>